[mgr]

show_hidden = true

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[open]
prepend_rules = [
	{ url = "*.duckdb", use = "duckdb" },
]

[opener]
duckdb = [
  { run = "clear; duckdb %*", block = true, desc = "duckdb" },
]
