#!/bin/sh

in_file=$1

rows=$(tput lines)

# export BAT_THEME="everforest-soft"
bat -r 0:$(((rows / 2))) -n $in_file

found=$(fdfind . $HOME/transforms/awk-sed -x basename | 
  fzf --style full --height=50% --preview "cat $in_file | sh $HOME/transforms/awk-sed/{}" --bind "focus:transform-header:cat $HOME/transforms/awk-sed/{}"
)

if [ -n "$found" ]; then
  out=$(cat $in_file | sh $HOME/transforms/awk-sed/"$found")
  echo "$out" > $in_file 
fi

