#!/bin/sh

in_file=$1

ext=""
read -p "Ext?: " ext

if [ -n "$ext" ]; then
  new_clip=$(cat $in_file | vipe --suffix=$ext)
  echo "$new_clip" > $in_file
else
  new_clip=$(cat $in_file | vipe)
  echo "$new_clip" > $in_file
fi

