#!/bin/sh

in_file=$1

rows=$(tput lines)

# export BAT_THEME="everforest-soft"
bat -r 0:$(((rows / 2))) -l json -n $in_file

found=$(fdfind . $HOME/transforms/jq -x basename | 
  fzf --style full --height=50% --preview "cat $in_file | jq -C -f $HOME/transforms/jq/{}" --bind "focus:transform-header:bat -l jq --color=always --wrap=never -p $HOME/transforms/jq/{} | sed -z 's/ \?\n/ /g' | sed 's/  \+//g'"
)

if [ -n "$found" ]; then
  out=$(cat $in_file | jq -f $HOME/transforms/jq/$found)
  echo "$out" > $in_file 
fi

