#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
# bspc config border_radius        8
bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          -5
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#343F44"
bspc config active_border_color		"#D3C6AA"
bspc config focused_border_color	"#A7C080"
bspc config presel_feedback_color	"#E69875"
bspc config urgent_border_color 	"#E67E80"

#Single monitor
bspc monitor -d 1 2 3 4 

#Dual monitor
#find out names with arandr or xrandr
# bspc monitor HDMI-3 -d 1 2 3 4 5
# bspc monitor DP-1 -d 6 7 8 9

#rullscreen applications
bspc rule -a onedrivegui state=floating

#Tiled applications
# bspc rule -a Zathura state=tiled

#open applications on specific workspaces
# bspc rule -a Google-chrome desktop='^5' follow=on
# bspc rule -a discord desktop='^4' follow=on



#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-3)
hsetroot -solid "#21272b"

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
