[font] 
normal = { family = "JetBrainsMono Nerd Font", style = "ExtraLight" }
italic = { family = "JetBrainsMono Nerd Font", style = "ExtraLight Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 18

[window]
option_as_alt = "Both"

[keyboard]
[[keyboard.bindings]]
key = "Enter" 
mods = "Control"      
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "6" 
mods = "Control"      
chars = "\u001b[54;5u"


# Colors (Everforest Dark)
# Default colors
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'


